name: continuous

on: [push]

jobs:
  ubuntu-latest:
    name: ubuntu-latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Buid the project if changes were made
        run: |
            chmod a+x ./build.sh
            ./build.sh ProjectA ProjectB
