name: continuous

on: [push]

jobs:
  ubuntu-latest:
    name: ubuntu-latest
    runs-on: ubuntu-latest
    steps:
      - name: Clone the repo
        uses: actions/checkout@v4.1.1
        with: 
          fetch-depth: 2
      
      - name: Buid the project if changes were made
        run: |
              chmod a+x ./build.sh
              ./build.sh ProjectA ProjectB

      - name: List docker images
        run: docker image ls
